services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./dev/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./landing:/var/www/landing
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  app: 
    container_name: water-regen-app
    build:
      context: .  # Path to directory with Dockerfile
      dockerfile: Dockerfile
    image: water-regen:latest
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    command: ["/bin/sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm run start:prod"]

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: